name    'rholt-puppet-plenv'
version '0.0.1'
author 'rholt'
license 'MIT'
summary 'plenv Perl Version Manager module'
description 'Puppet module for plenv Perl Version Manager'
project_page 'https://github.com/rholt/puppet-plenv'
